name: persistent_bottom_nav_bar_v2
description: A highly customizable bottom navigation bar for Flutter. Includes 17 prebuilt styles but can also be used with your custom style.

homepage: https://github.com/jb3rndt/PersistentBottomNavBarV2
repository: https://github.com/jb3rndt/PersistentBottomNavBarV2
version: 5.3.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ">=3.0.1 <6.0.0"

flutter:
  uses-material-design: true

cider:
  link_template:
    tag: https://github.com/jb3rndt/PersistentBottomNavBarV2/releases/tag/%tag% # initial release link template
    diff: https://github.com/jb3rndt/PersistentBottomNavBarV2/compare/%from%...%to% # subsequent releases link template
